# Neon tmux theme.
set -g status-style 'bg=#000000,fg=#8c9cc5'
set -g message-style 'bg=#11162a,fg=#dbe7ff'
set -g mode-style 'bg=#66e3ff,fg=#05070c'
set -g pane-border-style 'fg=#262b42'
set -g pane-active-border-style 'fg=#66e3ff'
set -g display-panes-colour '#805ad5'
set -g display-panes-active-colour '#66e3ff'
set -g window-status-separator ''
set -g window-status-style 'bg=#000000,fg=#697696'
set -g window-status-format ' #I:#W '
set -g window-status-current-style 'bg=#66e3ff,fg=#05070c,bold'
set -g window-status-current-format ' #I:#W '
set -g status-left '#[bg=#6d4aff,fg=#ffffff,bold] #S #[bg=#000000,fg=#2b3048] │ #[default]'
set -g status-left-length 40
set -g status-right '#[fg=#b79cff]#{pane_current_path}  #[fg=#66e3ff,bold]%H:%M '
set -g status-right-length 90
